---
- hosts: all
  connection: local

  vars:

    # Your project name
    ansible_project: 'default'

    # schedule is fed directly to cron
    schedule: '*/30 * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: '/var/lib/ansible/{{ ansible_project }}'

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    repo_url: https://github.com/1it/ansible-test

  tasks:
    - name: Create local directory to work from
      file:
        path: {{ workdir }}
        state: directory
        owner: root
        group: root
        mode: 0751

    - name: Create crontab entry to clone/pull git repository
      template:
        src: templates/etc_cron.d_ansible-pull.j2
        dest: /etc/cron.d/ansible-pull
        owner: root
        group: root
        mode: 0644

    - name: Create logrotate entry for ansible-pull.log
      template:
        src: templates/etc_logrotate.d_ansible-pull.j2
        dest: /etc/logrotate.d/ansible-pull
        owner: root
        group: root
        mode: 0644
